// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: rtpmanager/v1/rtpmanager.proto

package rtpmanagerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RTPManagerService_CreateSession_FullMethodName  = "/rtpmanager.v1.RTPManagerService/CreateSession"
	RTPManagerService_DestroySession_FullMethodName = "/rtpmanager.v1.RTPManagerService/DestroySession"
	RTPManagerService_PlayAudio_FullMethodName      = "/rtpmanager.v1.RTPManagerService/PlayAudio"
	RTPManagerService_StopAudio_FullMethodName      = "/rtpmanager.v1.RTPManagerService/StopAudio"
	RTPManagerService_Health_FullMethodName         = "/rtpmanager.v1.RTPManagerService/Health"
)

// RTPManagerServiceClient is the client API for RTPManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RTPManagerService handles media session lifecycle for SIP calls.
// Manages RTP port allocation, SDP generation, and audio streaming.
type RTPManagerServiceClient interface {
	// CreateSession allocates RTP ports and returns SDP for the session.
	// Called during INVITE processing to get media endpoint for SDP answer.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// DestroySession releases all resources associated with a session.
	// Called on BYE or call termination.
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	// PlayAudio starts audio playback to the remote endpoint.
	// Returns a stream of events including progress and completion.
	PlayAudio(ctx context.Context, in *PlayAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlaybackEvent], error)
	// StopAudio immediately stops any active playback for a session.
	StopAudio(ctx context.Context, in *StopAudioRequest, opts ...grpc.CallOption) (*StopAudioResponse, error)
	// Health checks if the service is operational.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type rTPManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRTPManagerServiceClient(cc grpc.ClientConnInterface) RTPManagerServiceClient {
	return &rTPManagerServiceClient{cc}
}

func (c *rTPManagerServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, RTPManagerService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTPManagerServiceClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, RTPManagerService_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTPManagerServiceClient) PlayAudio(ctx context.Context, in *PlayAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlaybackEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RTPManagerService_ServiceDesc.Streams[0], RTPManagerService_PlayAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlayAudioRequest, PlaybackEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RTPManagerService_PlayAudioClient = grpc.ServerStreamingClient[PlaybackEvent]

func (c *rTPManagerServiceClient) StopAudio(ctx context.Context, in *StopAudioRequest, opts ...grpc.CallOption) (*StopAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAudioResponse)
	err := c.cc.Invoke(ctx, RTPManagerService_StopAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTPManagerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RTPManagerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RTPManagerServiceServer is the server API for RTPManagerService service.
// All implementations must embed UnimplementedRTPManagerServiceServer
// for forward compatibility.
//
// RTPManagerService handles media session lifecycle for SIP calls.
// Manages RTP port allocation, SDP generation, and audio streaming.
type RTPManagerServiceServer interface {
	// CreateSession allocates RTP ports and returns SDP for the session.
	// Called during INVITE processing to get media endpoint for SDP answer.
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// DestroySession releases all resources associated with a session.
	// Called on BYE or call termination.
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	// PlayAudio starts audio playback to the remote endpoint.
	// Returns a stream of events including progress and completion.
	PlayAudio(*PlayAudioRequest, grpc.ServerStreamingServer[PlaybackEvent]) error
	// StopAudio immediately stops any active playback for a session.
	StopAudio(context.Context, *StopAudioRequest) (*StopAudioResponse, error)
	// Health checks if the service is operational.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRTPManagerServiceServer()
}

// UnimplementedRTPManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRTPManagerServiceServer struct{}

func (UnimplementedRTPManagerServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedRTPManagerServiceServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedRTPManagerServiceServer) PlayAudio(*PlayAudioRequest, grpc.ServerStreamingServer[PlaybackEvent]) error {
	return status.Error(codes.Unimplemented, "method PlayAudio not implemented")
}
func (UnimplementedRTPManagerServiceServer) StopAudio(context.Context, *StopAudioRequest) (*StopAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopAudio not implemented")
}
func (UnimplementedRTPManagerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRTPManagerServiceServer) mustEmbedUnimplementedRTPManagerServiceServer() {}
func (UnimplementedRTPManagerServiceServer) testEmbeddedByValue()                           {}

// UnsafeRTPManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RTPManagerServiceServer will
// result in compilation errors.
type UnsafeRTPManagerServiceServer interface {
	mustEmbedUnimplementedRTPManagerServiceServer()
}

func RegisterRTPManagerServiceServer(s grpc.ServiceRegistrar, srv RTPManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedRTPManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RTPManagerService_ServiceDesc, srv)
}

func _RTPManagerService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTPManagerServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTPManagerService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTPManagerServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTPManagerService_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTPManagerServiceServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTPManagerService_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTPManagerServiceServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTPManagerService_PlayAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayAudioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RTPManagerServiceServer).PlayAudio(m, &grpc.GenericServerStream[PlayAudioRequest, PlaybackEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RTPManagerService_PlayAudioServer = grpc.ServerStreamingServer[PlaybackEvent]

func _RTPManagerService_StopAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTPManagerServiceServer).StopAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTPManagerService_StopAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTPManagerServiceServer).StopAudio(ctx, req.(*StopAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTPManagerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTPManagerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTPManagerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTPManagerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RTPManagerService_ServiceDesc is the grpc.ServiceDesc for RTPManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RTPManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtpmanager.v1.RTPManagerService",
	HandlerType: (*RTPManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _RTPManagerService_CreateSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _RTPManagerService_DestroySession_Handler,
		},
		{
			MethodName: "StopAudio",
			Handler:    _RTPManagerService_StopAudio_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _RTPManagerService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayAudio",
			Handler:       _RTPManagerService_PlayAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rtpmanager/v1/rtpmanager.proto",
}
